<?php

namespace AppBundle\Repository;

/**
 * MaterialTypeStringsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialTypeStringsRepository extends \Doctrine\ORM\EntityRepository
{
}
