<?php

namespace AppBundle\Repository;

/**
 * OmicsExperimentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OmicsExperimentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
