<?php

namespace AppBundle\Repository;

/**
 * OmicsExperimentTypeStringsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OmicsExperimentTypeStringsRepository extends \Doctrine\ORM\EntityRepository
{
}
