<?php

namespace AppBundle\Repository;

/**
 * OmicsExperimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OmicsExperimentRepository extends \Doctrine\ORM\EntityRepository
{
}
