<?php

namespace AppBundle\Repository;

/**
 * OmicsExperimentSubTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OmicsExperimentSubTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
