<?php

namespace AppBundle\Repository;

/**
 * OmicsExperimentSubTypeStringsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SOmicsExperimentSubTypeStringsRepository extends \Doctrine\ORM\EntityRepository
{
}
