<?php

namespace AppBundle\Repository;

/**
 * SampleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SampleRepository extends \Doctrine\ORM\EntityRepository
{
}
