<?php

namespace AppBundle\Repository;

/**
 * SequenceRunRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceRunRepository extends \Doctrine\ORM\EntityRepository
{
}
