<?php

namespace AppBundle\Repository;

/**
 * StatusStringsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusStringsRepository extends \Doctrine\ORM\EntityRepository
{
}
